apiVersion: v1alpha1
kind: Setting
metadata:
  name: theme-anatole-setting
spec:
  forms:
    - group: basic
      label: 基本设置
      formSchema:
        - $formkit: select
          name: sidebar_width
          label: 侧边栏宽度
          options:
            "20%": 20%
            "30%": 30%
            "40%": 40%
            "50%": 50%
          value: "40%"
        - $formkit: text
          name: sidebar_background
          label: 侧边栏背景图
        - $formkit: text
          name: icon
          label: 左上角图标
        - $formkit: radio
          name: avatar_logo
          label: 圆形 Logo
          options:
            - label: 开启
              value: true
            - label: 关闭
              value: false
          value: false
    - group: social
      label: 社交资料
      formSchema:
        - $formkit: radio
          name: rss
          label: RSS
          options:
            - label: 开启
              value: true
            - label: 关闭
              value: false
          value: true
        - $formkit: text
          name: twitter
          label: Twitter
          help: "只需填入 Twitter 用户名即可"
        - $formkit: text
          name: facebook
          label: Facebook
          help: "只需填入 Facebook 用户名即可"
        - $formkit: text
          name: instagram
          label: Instagram
          help: "只需填入 Instagram 用户名即可"
        - $formkit: text
          name: weibo
          label: 微博
          help: "只需填入微博 Id 即可"
        - $formkit: text
          name: email
          label: Email
          help: "只需填入邮箱地址即可"
        - $formkit: text
          name: github
          label: GitHub
          help: "只需填入 GitHub 用户名即可"
        - $formkit: text
          name: qq
          label: QQ
          help: "只需填入 QQ 号即可"
        - $formkit: text
          name: telegram
          label: Telegram
          help: "只需填入 Telegram Id 即可"
